import { BudgetLine, Typology, RoofType } from './types';

// HR Pay Rates
export const PAY_RATES = {
  'Supervisor': 250,
  'Encargado': 250,
  'Maestro': 200,
  'Albañil': 175,
  'Ayudante': 125,
  'Peón': 100
};

// Quoting Services Base Prices
export const QUOTE_SERVICES = [
  { name: 'Planos de Registro', price: 400, unit: 'm2' }, 
  { name: 'Ante-proyecto (1 nivel)', price: 3000, unit: 'global' },
  { name: 'Ante-proyecto (>120m2)', price: 5000, unit: 'global' },
  { name: 'Avalúos', price: 1.50, unit: 'm2' },
  { name: 'Topografía', price: 2.00, unit: 'm2' },
  { name: 'Replanteos', price: 1.50, unit: 'm2' },
  { name: 'Trazo Calles/Drenajes', price: 4.50, unit: 'ml' },
  { name: 'Planificación Residencial', price: 8000, unit: 'global' },
  { name: 'Planificación Comercial', price: 50000, unit: 'global' },
  { name: 'Planificación Industrial', price: 50000, unit: 'global' },
  { name: 'Planificación Civil', price: 25000, unit: 'global' },
  { name: 'Planificación Pública', price: 15000, unit: 'global' },
];

// APU Factors
export const AUI_FACTOR = 0.35; // Admin 20% + Utility 12% + Unforeseen 3%
export const IVA_FACTOR = 0.12;

export const calculateAPU = (directCost: number, customIndirectFactor?: number) => {
  const factor = customIndirectFactor !== undefined ? customIndirectFactor : AUI_FACTOR;
  const indirectCost = directCost * factor;
  const priceNoTax = directCost + indirectCost;
  const tax = priceNoTax * IVA_FACTOR;
  const finalPrice = priceNoTax + tax;
  return { indirectCost, priceNoTax, tax, finalPrice };
};

// Mock Database of Construction Items (Renglones) for defaults
// Lists approx 30 items per typology in chronological order
export const DEFAULT_BUDGET_LINES: Record<Typology, Partial<BudgetLine>[]> = {
  'RESIDENCIAL': [
    { name: '1. Limpieza y chapeo', unit: 'm2', laborCost: 15, equipmentCost: 5, materials: [] },
    { name: '2. Trazo y nivelación', unit: 'm2', laborCost: 12, equipmentCost: 3, materials: [{name: 'Cal', unit: 'lbs', quantityPerUnit: 0.5, unitPrice: 5}, {name: 'Madera reglas', unit: 'pt', quantityPerUnit: 0.5, unitPrice: 12}] },
    { name: '3. Excavación cimentación', unit: 'm3', laborCost: 80, equipmentCost: 0, materials: [] },
    { name: '4. Solera de humedad', unit: 'ml', laborCost: 45, equipmentCost: 5, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 0.03, unitPrice: 1200}, {name: 'Acero', unit: 'qq', quantityPerUnit: 0.08, unitPrice: 500}] },
    { name: '5. Cimiento corrido', unit: 'ml', laborCost: 160, equipmentCost: 25, materials: [{name: 'Concreto 3000psi', unit: 'm3', quantityPerUnit: 0.10, unitPrice: 1200}, {name: 'Acero Refuerzo', unit: 'qq', quantityPerUnit: 0.18, unitPrice: 450}] },
    { name: '5. Cimentación (Zapatas)', unit: 'm3', laborCost: 350, equipmentCost: 50, materials: [{name: 'Concreto 3000psi', unit: 'm3', quantityPerUnit: 1.05, unitPrice: 1200}, {name: 'Acero Refuerzo', unit: 'qq', quantityPerUnit: 1.5, unitPrice: 450}] },
    { name: '6. Levantado de muros', unit: 'm2', laborCost: 85, equipmentCost: 5, materials: [{name: 'Block 35kg', unit: 'unidad', quantityPerUnit: 12.5, unitPrice: 6.50}, {name: 'Mezcla', unit: 'm3', quantityPerUnit: 0.02, unitPrice: 800}] },
    { name: '7. Columnas principales', unit: 'ml', laborCost: 120, equipmentCost: 20, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 0.04, unitPrice: 1200}, {name: 'Acero', unit: 'qq', quantityPerUnit: 0.2, unitPrice: 500}] },
    { name: '8. Soleras intermedias', unit: 'ml', laborCost: 60, equipmentCost: 10, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 0.02, unitPrice: 1200}, {name: 'Acero', unit: 'qq', quantityPerUnit: 0.05, unitPrice: 500}] },
    { name: '9. Inst. Drenajes (Suelo)', unit: 'ml', laborCost: 35, equipmentCost: 0, materials: [{name: 'Tubo PVC 4"', unit: 'tubo', quantityPerUnit: 0.17, unitPrice: 180}, {name: 'Accesorios', unit: 'gl', quantityPerUnit: 1, unitPrice: 25}] },
    { name: '10. Inst. Agua Potable (Suelo)', unit: 'ml', laborCost: 25, equipmentCost: 0, materials: [{name: 'Tubo PVC 3/4"', unit: 'tubo', quantityPerUnit: 0.17, unitPrice: 45}] },
    { name: '11. Vigas de amarre', unit: 'ml', laborCost: 130, equipmentCost: 25, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 0.05, unitPrice: 1200}, {name: 'Acero', unit: 'qq', quantityPerUnit: 0.25, unitPrice: 500}] },
    { name: '12. Losa de entrepiso', unit: 'm2', laborCost: 150, equipmentCost: 40, materials: [{name: 'Vigueta/Bovedilla', unit: 'm2', quantityPerUnit: 1, unitPrice: 280}, {name: 'Electro malla', unit: 'm2', quantityPerUnit: 1.1, unitPrice: 15}, {name: 'Concreto', unit: 'm3', quantityPerUnit: 0.08, unitPrice: 1200}] },
    { name: '13. Gradas de concreto', unit: 'ml', laborCost: 200, equipmentCost: 10, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 0.15, unitPrice: 1200}, {name: 'Acero', unit: 'qq', quantityPerUnit: 0.1, unitPrice: 500}] },
    { name: '14. Inst. Eléctrica (Ductos)', unit: 'puntos', laborCost: 45, equipmentCost: 0, materials: [{name: 'Ducto poliducto', unit: 'rollo', quantityPerUnit: 0.1, unitPrice: 150}, {name: 'Cajas rectangulares', unit: 'u', quantityPerUnit: 1, unitPrice: 5}] },
    { name: '15. Repello de muros', unit: 'm2', laborCost: 40, equipmentCost: 5, materials: [{name: 'Mezcla repello', unit: 'm3', quantityPerUnit: 0.02, unitPrice: 750}] },
    { name: '16. Cernido de muros', unit: 'm2', laborCost: 35, equipmentCost: 2, materials: [{name: 'Mezcla cernido', unit: 'm3', quantityPerUnit: 0.005, unitPrice: 900}] },
    { name: '17. Masillado de losa', unit: 'm2', laborCost: 30, equipmentCost: 0, materials: [{name: 'Mortero', unit: 'm3', quantityPerUnit: 0.01, unitPrice: 800}] },
    { name: '18. Impermeabilización', unit: 'm2', laborCost: 25, equipmentCost: 5, materials: [{name: 'Impermeabilizante', unit: 'gal', quantityPerUnit: 0.1, unitPrice: 150}] },
    { name: '19. Piso cerámico', unit: 'm2', laborCost: 65, equipmentCost: 5, materials: [{name: 'Piso', unit: 'm2', quantityPerUnit: 1.05, unitPrice: 85}, {name: 'Pegamix', unit: 'saco', quantityPerUnit: 0.2, unitPrice: 45}] },
    { name: '20. Azulejo baños', unit: 'm2', laborCost: 70, equipmentCost: 5, materials: [{name: 'Azulejo', unit: 'm2', quantityPerUnit: 1.05, unitPrice: 90}, {name: 'Pegamix', unit: 'saco', quantityPerUnit: 0.2, unitPrice: 45}] },
    { name: '21. Ventanería', unit: 'm2', laborCost: 0, equipmentCost: 0, materials: [{name: 'Ventana Aluminio', unit: 'm2', quantityPerUnit: 1, unitPrice: 650}] },
    { name: '22. Puertas', unit: 'unidad', laborCost: 100, equipmentCost: 0, materials: [{name: 'Puerta y marco', unit: 'u', quantityPerUnit: 1, unitPrice: 1200}] },
    { name: '23. Cableado eléctrico', unit: 'ml', laborCost: 15, equipmentCost: 0, materials: [{name: 'Cable THHN', unit: 'ml', quantityPerUnit: 3, unitPrice: 8}] },
    { name: '24. Artefactos eléctricos', unit: 'unidad', laborCost: 15, equipmentCost: 0, materials: [{name: 'Tomacorriente/Interruptor', unit: 'u', quantityPerUnit: 1, unitPrice: 35}] },
    { name: '25. Luminarias', unit: 'unidad', laborCost: 25, equipmentCost: 5, materials: [{name: 'Lámpara LED', unit: 'u', quantityPerUnit: 1, unitPrice: 120}] },
    { name: '26. Artefactos sanitarios', unit: 'unidad', laborCost: 150, equipmentCost: 0, materials: [{name: 'Inodoro/Lavamanos', unit: 'set', quantityPerUnit: 1, unitPrice: 1500}] },
    { name: '27. Muebles de cocina', unit: 'ml', laborCost: 0, equipmentCost: 0, materials: [{name: 'Gabinete aéreo/base', unit: 'ml', quantityPerUnit: 1, unitPrice: 1800}] },
    { name: '28. Closets', unit: 'm2', laborCost: 0, equipmentCost: 0, materials: [{name: 'Closet melanina', unit: 'm2', quantityPerUnit: 1, unitPrice: 950}] },
    { name: '29. Pintura general', unit: 'm2', laborCost: 25, equipmentCost: 2, materials: [{name: 'Pintura látex', unit: 'gal', quantityPerUnit: 0.04, unitPrice: 250}] },
    { name: '30. Limpieza final', unit: 'global', laborCost: 1500, equipmentCost: 200, materials: [{name: 'Materiales limpieza', unit: 'gl', quantityPerUnit: 1, unitPrice: 500}] },
  ],
  'COMERCIAL': [
    { name: '1. Descapote y limpieza', unit: 'm2', laborCost: 10, equipmentCost: 20, materials: [] },
    { name: '2. Movimiento de tierras', unit: 'm3', laborCost: 0, equipmentCost: 80, materials: [] },
    { name: '3. Cimentación aislada', unit: 'm3', laborCost: 350, equipmentCost: 80, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 1, unitPrice: 1250}, {name: 'Acero', unit: 'qq', quantityPerUnit: 1.8, unitPrice: 480}] },
    { name: '4. Estructura metálica principal', unit: 'kg', laborCost: 8, equipmentCost: 4, materials: [{name: 'Acero estructural', unit: 'kg', quantityPerUnit: 1.05, unitPrice: 14}] },
    { name: '5. Entrepiso losa cero', unit: 'm2', laborCost: 80, equipmentCost: 20, materials: [{name: 'Lámina losacero', unit: 'm2', quantityPerUnit: 1, unitPrice: 180}, {name: 'Concreto', unit: 'm3', quantityPerUnit: 0.1, unitPrice: 1250}] },
    { name: '6. Muros perimetrales', unit: 'm2', laborCost: 90, equipmentCost: 10, materials: [{name: 'Block', unit: 'u', quantityPerUnit: 12.5, unitPrice: 6.5}] },
    { name: '7. Tabiquería tabla yeso', unit: 'm2', laborCost: 45, equipmentCost: 5, materials: [{name: 'Planchas yeso', unit: 'u', quantityPerUnit: 0.35, unitPrice: 65}, {name: 'Estructura', unit: 'ml', quantityPerUnit: 2, unitPrice: 20}] },
    { name: '8. Inst. Contra Incendios', unit: 'salida', laborCost: 200, equipmentCost: 50, materials: [{name: 'Tubería HG', unit: 'ml', quantityPerUnit: 3, unitPrice: 150}, {name: 'Rociador', unit: 'u', quantityPerUnit: 1, unitPrice: 85}] },
    { name: '9. Ductos A/C', unit: 'ml', laborCost: 120, equipmentCost: 20, materials: [{name: 'Lámina ducto', unit: 'm2', quantityPerUnit: 1.5, unitPrice: 120}] },
    { name: '10. Inst. Eléctrica comercial', unit: 'punto', laborCost: 80, equipmentCost: 10, materials: [{name: 'EMT y cable', unit: 'gl', quantityPerUnit: 1, unitPrice: 250}] },
    { name: '11. Cielos falsos', unit: 'm2', laborCost: 35, equipmentCost: 5, materials: [{name: 'Baldosa fibra', unit: 'm2', quantityPerUnit: 1.05, unitPrice: 85}, {name: 'Suspensión', unit: 'm2', quantityPerUnit: 1, unitPrice: 40}] },
    { name: '12. Fachada de vidrio', unit: 'm2', laborCost: 0, equipmentCost: 0, materials: [{name: 'Vidrio templado', unit: 'm2', quantityPerUnit: 1, unitPrice: 1800}] },
    { name: '13. Cortinas metálicas', unit: 'm2', laborCost: 0, equipmentCost: 0, materials: [{name: 'Cortina enrollable', unit: 'm2', quantityPerUnit: 1, unitPrice: 900}] },
    { name: '14. Pisos alto tráfico', unit: 'm2', laborCost: 70, equipmentCost: 10, materials: [{name: 'Porcelanato', unit: 'm2', quantityPerUnit: 1.05, unitPrice: 220}] },
    { name: '15. Pintura epóxica', unit: 'm2', laborCost: 45, equipmentCost: 10, materials: [{name: 'Epóxico', unit: 'gal', quantityPerUnit: 0.05, unitPrice: 600}] },
    { name: '16. Señalización', unit: 'global', laborCost: 1000, equipmentCost: 0, materials: [{name: 'Señales', unit: 'gl', quantityPerUnit: 1, unitPrice: 2000}] },
    { name: '17. Baños públicos', unit: 'm2', laborCost: 2000, equipmentCost: 0, materials: [{name: 'Particiones y sanitarios', unit: 'gl', quantityPerUnit: 1, unitPrice: 8000}] },
    { name: '18. Iluminación LED paneles', unit: 'unidad', laborCost: 50, equipmentCost: 10, materials: [{name: 'Panel 60x60', unit: 'u', quantityPerUnit: 1, unitPrice: 350}] },
    { name: '19. Sistema de sonido', unit: 'global', laborCost: 2500, equipmentCost: 0, materials: [{name: 'Parlantes y amp', unit: 'gl', quantityPerUnit: 1, unitPrice: 15000}] },
    { name: '20. Red de datos', unit: 'punto', laborCost: 150, equipmentCost: 20, materials: [{name: 'Cable UTP/Faceplate', unit: 'gl', quantityPerUnit: 1, unitPrice: 180}] },
    { name: '21. Cámaras seguridad', unit: 'unidad', laborCost: 200, equipmentCost: 50, materials: [{name: 'Cámara IP', unit: 'u', quantityPerUnit: 1, unitPrice: 800}] },
    { name: '22. Transformador', unit: 'unidad', laborCost: 5000, equipmentCost: 2000, materials: [{name: 'Transformador pad', unit: 'u', quantityPerUnit: 1, unitPrice: 45000}] },
    { name: '23. Planta emergencia', unit: 'unidad', laborCost: 3000, equipmentCost: 1500, materials: [{name: 'Generador', unit: 'u', quantityPerUnit: 1, unitPrice: 85000}] },
    { name: '24. Cisterna agua', unit: 'global', laborCost: 15000, equipmentCost: 2000, materials: [{name: 'Concreto y equipos', unit: 'gl', quantityPerUnit: 1, unitPrice: 25000}] },
    { name: '25. Bombas agua', unit: 'global', laborCost: 2000, equipmentCost: 0, materials: [{name: 'Equipo hidroneumático', unit: 'gl', quantityPerUnit: 1, unitPrice: 12000}] },
    { name: '26. Áreas verdes', unit: 'm2', laborCost: 25, equipmentCost: 5, materials: [{name: 'Grama y plantas', unit: 'm2', quantityPerUnit: 1, unitPrice: 80}] },
    { name: '27. Adoquín parqueo', unit: 'm2', laborCost: 40, equipmentCost: 10, materials: [{name: 'Adoquín tráfico', unit: 'm2', quantityPerUnit: 1.05, unitPrice: 110}] },
    { name: '28. Topes llanta', unit: 'unidad', laborCost: 50, equipmentCost: 0, materials: [{name: 'Tope concreto', unit: 'u', quantityPerUnit: 1, unitPrice: 150}] },
    { name: '29. Limpieza vidrios altura', unit: 'global', laborCost: 5000, equipmentCost: 1500, materials: [] },
    { name: '30. Recepción final', unit: 'global', laborCost: 0, equipmentCost: 0, materials: [] },
  ],
  'INDUSTRIAL': [
    { name: '1. Topografía y trazo', unit: 'm2', laborCost: 5, equipmentCost: 5, materials: [{name: 'Estacas/Cal', unit: 'gl', quantityPerUnit: 0.01, unitPrice: 100}] },
    { name: '2. Movimiento tierras masivo', unit: 'm3', laborCost: 0, equipmentCost: 65, materials: [] },
    { name: '3. Compactación base', unit: 'm2', laborCost: 10, equipmentCost: 25, materials: [{name: 'Material selecto', unit: 'm3', quantityPerUnit: 0.2, unitPrice: 180}] },
    { name: '4. Cimentación naves', unit: 'm3', laborCost: 400, equipmentCost: 100, materials: [{name: 'Concreto 4000psi', unit: 'm3', quantityPerUnit: 1, unitPrice: 1400}, {name: 'Pernos anclaje', unit: 'u', quantityPerUnit: 12, unitPrice: 150}] },
    { name: '5. Estructura marcos acero', unit: 'kg', laborCost: 10, equipmentCost: 15, materials: [{name: 'Acero W', unit: 'kg', quantityPerUnit: 1, unitPrice: 16}] },
    { name: '6. Montaje costaneras', unit: 'ml', laborCost: 15, equipmentCost: 10, materials: [{name: 'Costanera', unit: 'ml', quantityPerUnit: 1, unitPrice: 45}] },
    { name: '7. Cubierta techo lámina', unit: 'm2', laborCost: 25, equipmentCost: 10, materials: [{name: 'Lámina Aluzinc', unit: 'm2', quantityPerUnit: 1.1, unitPrice: 90}] },
    { name: '8. Piso industrial', unit: 'm2', laborCost: 60, equipmentCost: 40, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 0.15, unitPrice: 1400}, {name: 'Endurecedor', unit: 'kg', quantityPerUnit: 3, unitPrice: 25}] },
    { name: '9. Juntas dilatación', unit: 'ml', laborCost: 15, equipmentCost: 15, materials: [{name: 'Sello poliuretano', unit: 'ml', quantityPerUnit: 1, unitPrice: 45}] },
    { name: '10. Muros perimetrales block', unit: 'm2', laborCost: 85, equipmentCost: 5, materials: [{name: 'Block 50kg', unit: 'u', quantityPerUnit: 12.5, unitPrice: 8}] },
    { name: '11. Portones industriales', unit: 'unidad', laborCost: 1500, equipmentCost: 500, materials: [{name: 'Portón corredizo', unit: 'u', quantityPerUnit: 1, unitPrice: 15000}] },
    { name: '12. Rampas de carga', unit: 'unidad', laborCost: 2000, equipmentCost: 500, materials: [{name: 'Nivelador andén', unit: 'u', quantityPerUnit: 1, unitPrice: 25000}] },
    { name: '13. Iluminación High Bay', unit: 'unidad', laborCost: 150, equipmentCost: 100, materials: [{name: 'Lámpara industrial', unit: 'u', quantityPerUnit: 1, unitPrice: 1200}] },
    { name: '14. Red eléctrica trifásica', unit: 'ml', laborCost: 100, equipmentCost: 50, materials: [{name: 'Cableado y ductos', unit: 'ml', quantityPerUnit: 1, unitPrice: 300}] },
    { name: '15. Aire comprimido', unit: 'ml', laborCost: 45, equipmentCost: 10, materials: [{name: 'Tubería aluminio/galv', unit: 'ml', quantityPerUnit: 1, unitPrice: 120}] },
    { name: '16. Ventilación eólica', unit: 'unidad', laborCost: 250, equipmentCost: 0, materials: [{name: 'Extractor eólico', unit: 'u', quantityPerUnit: 1, unitPrice: 1800}] },
    { name: '17. Sistema pararrayos', unit: 'global', laborCost: 5000, equipmentCost: 1000, materials: [{name: 'Puntas y cable', unit: 'gl', quantityPerUnit: 1, unitPrice: 12000}] },
    { name: '18. Malla perimetral', unit: 'ml', laborCost: 60, equipmentCost: 10, materials: [{name: 'Malla y postes', unit: 'ml', quantityPerUnit: 1, unitPrice: 180}] },
    { name: '19. Garita seguridad', unit: 'global', laborCost: 15000, equipmentCost: 2000, materials: [{name: 'Materiales garita', unit: 'gl', quantityPerUnit: 1, unitPrice: 25000}] },
    { name: '20. Pozo absorción', unit: 'unidad', laborCost: 5000, equipmentCost: 3000, materials: [{name: 'Ladrillo y grava', unit: 'gl', quantityPerUnit: 1, unitPrice: 4000}] },
    { name: '21. Planta tratamiento', unit: 'global', laborCost: 25000, equipmentCost: 5000, materials: [{name: 'Equipos y obra civil', unit: 'gl', quantityPerUnit: 1, unitPrice: 65000}] },
    { name: '22. Señalización industrial', unit: 'global', laborCost: 2000, equipmentCost: 0, materials: [{name: 'Pintura tráfico', unit: 'gl', quantityPerUnit: 1, unitPrice: 3500}] },
    { name: '23. Defensas metálicas', unit: 'ml', laborCost: 80, equipmentCost: 20, materials: [{name: 'Defensa', unit: 'ml', quantityPerUnit: 1, unitPrice: 450}] },
    { name: '24. Cuartos fríos', unit: 'm2', laborCost: 200, equipmentCost: 50, materials: [{name: 'Panel refrigeración', unit: 'm2', quantityPerUnit: 1, unitPrice: 650}] },
    { name: '25. Oficinas mezzanine', unit: 'm2', laborCost: 1200, equipmentCost: 100, materials: [{name: 'Estructura y acabados', unit: 'm2', quantityPerUnit: 1, unitPrice: 2500}] },
    { name: '26. Racks almacenamiento', unit: 'posición', laborCost: 50, equipmentCost: 20, materials: [{name: 'Estructura rack', unit: 'pos', quantityPerUnit: 1, unitPrice: 450}] },
    { name: '27. Báscula camiones', unit: 'global', laborCost: 10000, equipmentCost: 5000, materials: [{name: 'Equipo báscula', unit: 'gl', quantityPerUnit: 1, unitPrice: 120000}] },
    { name: '28. Transformadores', unit: 'unidad', laborCost: 5000, equipmentCost: 2000, materials: [{name: 'Transformador 500kVA', unit: 'u', quantityPerUnit: 1, unitPrice: 85000}] },
    { name: '29. Pruebas equipos', unit: 'global', laborCost: 5000, equipmentCost: 0, materials: [] },
    { name: '30. Limpieza industrial', unit: 'global', laborCost: 8000, equipmentCost: 3000, materials: [] },
  ],
  'CIVIL': [
    { name: '1. Desmonte y limpieza', unit: 'ha', laborCost: 2500, equipmentCost: 5000, materials: [] },
    { name: '2. Excavación no clasificada', unit: 'm3', laborCost: 15, equipmentCost: 35, materials: [] },
    { name: '3. Excavación en roca', unit: 'm3', laborCost: 50, equipmentCost: 250, materials: [{name: 'Explosivos', unit: 'gl', quantityPerUnit: 1, unitPrice: 45}] },
    { name: '4. Relleno compactado', unit: 'm3', laborCost: 25, equipmentCost: 60, materials: [{name: 'Material', unit: 'm3', quantityPerUnit: 1.2, unitPrice: 80}] },
    { name: '5. Sub-base granular', unit: 'm3', laborCost: 30, equipmentCost: 70, materials: [{name: 'Material sub-base', unit: 'm3', quantityPerUnit: 1.2, unitPrice: 120}] },
    { name: '6. Base triturada', unit: 'm3', laborCost: 35, equipmentCost: 80, materials: [{name: 'Material base', unit: 'm3', quantityPerUnit: 1.2, unitPrice: 180}] },
    { name: '7. Imprimación asfáltica', unit: 'gl', laborCost: 5, equipmentCost: 15, materials: [{name: 'Emulsión', unit: 'gl', quantityPerUnit: 0.3, unitPrice: 35}] },
    { name: '8. Carpeta asfáltica', unit: 'ton', laborCost: 40, equipmentCost: 120, materials: [{name: 'Mezcla asfáltica', unit: 'ton', quantityPerUnit: 1, unitPrice: 850}] },
    { name: '9. Concreto hidráulico', unit: 'm3', laborCost: 200, equipmentCost: 150, materials: [{name: 'Concreto 4000psi', unit: 'm3', quantityPerUnit: 1.05, unitPrice: 1350}] },
    { name: '10. Cunetas revestidas', unit: 'ml', laborCost: 80, equipmentCost: 20, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 0.1, unitPrice: 1200}] },
    { name: '11. Alcantarillas tubería', unit: 'ml', laborCost: 150, equipmentCost: 80, materials: [{name: 'Tubo concreto 36"', unit: 'u', quantityPerUnit: 1, unitPrice: 1800}] },
    { name: '12. Cajas y cabezales', unit: 'unidad', laborCost: 1200, equipmentCost: 300, materials: [{name: 'Concreto/Acero', unit: 'gl', quantityPerUnit: 1, unitPrice: 2500}] },
    { name: '13. Muro contención concreto', unit: 'm3', laborCost: 400, equipmentCost: 100, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 1, unitPrice: 1250}, {name: 'Acero', unit: 'qq', quantityPerUnit: 1.5, unitPrice: 500}] },
    { name: '14. Gaviones', unit: 'm3', laborCost: 180, equipmentCost: 50, materials: [{name: 'Piedra y malla', unit: 'm3', quantityPerUnit: 1, unitPrice: 450}] },
    { name: '15. Pilotes cimentación', unit: 'ml', laborCost: 300, equipmentCost: 500, materials: [{name: 'Concreto/Acero', unit: 'ml', quantityPerUnit: 1, unitPrice: 800}] },
    { name: '16. Vigas puente', unit: 'ml', laborCost: 500, equipmentCost: 1000, materials: [{name: 'Viga prefabricada', unit: 'ml', quantityPerUnit: 1, unitPrice: 3500}] },
    { name: '17. Losa puente', unit: 'm3', laborCost: 500, equipmentCost: 200, materials: [{name: 'Concreto 5000psi', unit: 'm3', quantityPerUnit: 1, unitPrice: 1600}] },
    { name: '18. Barandas puente', unit: 'ml', laborCost: 150, equipmentCost: 50, materials: [{name: 'Acero/Concreto', unit: 'ml', quantityPerUnit: 1, unitPrice: 600}] },
    { name: '19. Juntas dilatación puente', unit: 'ml', laborCost: 300, equipmentCost: 100, materials: [{name: 'Junta neopreno', unit: 'ml', quantityPerUnit: 1, unitPrice: 2500}] },
    { name: '20. Señalización vertical', unit: 'unidad', laborCost: 150, equipmentCost: 50, materials: [{name: 'Señal y poste', unit: 'u', quantityPerUnit: 1, unitPrice: 850}] },
    { name: '21. Señalización horizontal', unit: 'km', laborCost: 1500, equipmentCost: 2500, materials: [{name: 'Pintura termo', unit: 'gl', quantityPerUnit: 1, unitPrice: 8000}] },
    { name: '22. Vialetas', unit: 'unidad', laborCost: 15, equipmentCost: 5, materials: [{name: 'Vialeta', unit: 'u', quantityPerUnit: 1, unitPrice: 25}] },
    { name: '23. Defensas flex-beam', unit: 'ml', laborCost: 60, equipmentCost: 40, materials: [{name: 'Defensa metal', unit: 'ml', quantityPerUnit: 1, unitPrice: 420}] },
    { name: '24. Hidrosiembra taludes', unit: 'm2', laborCost: 15, equipmentCost: 25, materials: [{name: 'Semilla/Mulch', unit: 'm2', quantityPerUnit: 1, unitPrice: 35}] },
    { name: '25. Anclajes talud', unit: 'ml', laborCost: 200, equipmentCost: 150, materials: [{name: 'Perno y lechada', unit: 'ml', quantityPerUnit: 1, unitPrice: 350}] },
    { name: '26. Drenajes franceses', unit: 'ml', laborCost: 80, equipmentCost: 20, materials: [{name: 'Geotextil/Grava', unit: 'ml', quantityPerUnit: 1, unitPrice: 150}] },
    { name: '27. Bordillos', unit: 'ml', laborCost: 45, equipmentCost: 15, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 0.04, unitPrice: 1200}] },
    { name: '28. Aceras', unit: 'm2', laborCost: 60, equipmentCost: 10, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 0.1, unitPrice: 1200}] },
    { name: '29. Iluminación vial', unit: 'unidad', laborCost: 500, equipmentCost: 1500, materials: [{name: 'Poste y luminaria', unit: 'u', quantityPerUnit: 1, unitPrice: 5000}] },
    { name: '30. Limpieza final obra', unit: 'global', laborCost: 10000, equipmentCost: 5000, materials: [] },
  ],
  'PUBLICA': [
    { name: '1. Cerramiento provisional', unit: 'ml', laborCost: 35, equipmentCost: 5, materials: [{name: 'Lámina/Madera', unit: 'ml', quantityPerUnit: 1, unitPrice: 80}] },
    { name: '2. Demoliciones', unit: 'm3', laborCost: 150, equipmentCost: 200, materials: [] },
    { name: '3. Trazo y estaquillado', unit: 'm2', laborCost: 10, equipmentCost: 5, materials: [{name: 'Cal/Estacas', unit: 'gl', quantityPerUnit: 0.01, unitPrice: 100}] },
    { name: '4. Movimiento de tierras', unit: 'm3', laborCost: 20, equipmentCost: 60, materials: [] },
    { name: '5. Cimentación corrida', unit: 'm3', laborCost: 350, equipmentCost: 50, materials: [{name: 'Concreto', unit: 'm3', quantityPerUnit: 1, unitPrice: 1200}, {name: 'Acero', unit: 'qq', quantityPerUnit: 1.5, unitPrice: 480}] },
    { name: '6. Muros de carga', unit: 'm2', laborCost: 90, equipmentCost: 10, materials: [{name: 'Ladrillo/Block', unit: 'u', quantityPerUnit: 13, unitPrice: 7}] },
    { name: '7. Estructura de techo', unit: 'm2', laborCost: 60, equipmentCost: 10, materials: [{name: 'Estructura metal', unit: 'm2', quantityPerUnit: 1, unitPrice: 250}] },
    { name: '8. Cubierta techo', unit: 'm2', laborCost: 30, equipmentCost: 5, materials: [{name: 'Lámina', unit: 'm2', quantityPerUnit: 1.1, unitPrice: 85}] },
    { name: '9. Instalaciones hidráulicas', unit: 'global', laborCost: 5000, equipmentCost: 500, materials: [{name: 'Tubería y accesorios', unit: 'gl', quantityPerUnit: 1, unitPrice: 8000}] },
    { name: '10. Instalaciones sanitarias', unit: 'global', laborCost: 6000, equipmentCost: 500, materials: [{name: 'Tubería drenaje', unit: 'gl', quantityPerUnit: 1, unitPrice: 9000}] },
    { name: '11. Red eléctrica', unit: 'salida', laborCost: 60, equipmentCost: 0, materials: [{name: 'Materiales elect', unit: 'gl', quantityPerUnit: 1, unitPrice: 150}] },
    { name: '12. Pisos granito/cerámico', unit: 'm2', laborCost: 80, equipmentCost: 20, materials: [{name: 'Piso', unit: 'm2', quantityPerUnit: 1.05, unitPrice: 120}] },
    { name: '13. Ventanería seguridad', unit: 'm2', laborCost: 50, equipmentCost: 0, materials: [{name: 'Ventana metal', unit: 'm2', quantityPerUnit: 1, unitPrice: 450}] },
    { name: '14. Puertas metal', unit: 'unidad', laborCost: 150, equipmentCost: 50, materials: [{name: 'Puerta metal', unit: 'u', quantityPerUnit: 1, unitPrice: 1500}] },
    { name: '15. Artefactos sanitarios antivandálicos', unit: 'unidad', laborCost: 200, equipmentCost: 0, materials: [{name: 'Sanitario acero/losa', unit: 'u', quantityPerUnit: 1, unitPrice: 2500}] },
    { name: '16. Pintura antibacterial', unit: 'm2', laborCost: 40, equipmentCost: 5, materials: [{name: 'Pintura esp', unit: 'gal', quantityPerUnit: 0.05, unitPrice: 450}] },
    { name: '17. Rampas discapacitados', unit: 'ml', laborCost: 150, equipmentCost: 20, materials: [{name: 'Concreto/Baranda', unit: 'ml', quantityPerUnit: 1, unitPrice: 600}] },
    { name: '18. Muro perimetral', unit: 'ml', laborCost: 300, equipmentCost: 20, materials: [{name: 'Block y concreto', unit: 'ml', quantityPerUnit: 1, unitPrice: 800}] },
    { name: '19. Cancha polideportiva', unit: 'm2', laborCost: 50, equipmentCost: 40, materials: [{name: 'Concreto y pintura', unit: 'm2', quantityPerUnit: 1, unitPrice: 350}] },
    { name: '20. Juegos infantiles', unit: 'global', laborCost: 2000, equipmentCost: 500, materials: [{name: 'Set juegos', unit: 'gl', quantityPerUnit: 1, unitPrice: 15000}] },
    { name: '21. Mobiliario urbano', unit: 'global', laborCost: 1500, equipmentCost: 0, materials: [{name: 'Bancas/Basureros', unit: 'gl', quantityPerUnit: 1, unitPrice: 8000}] },
    { name: '22. Cisterna y bomba', unit: 'global', laborCost: 10000, equipmentCost: 2000, materials: [{name: 'Equipo completo', unit: 'gl', quantityPerUnit: 1, unitPrice: 35000}] },
    { name: '23. Planta tratamiento', unit: 'global', laborCost: 20000, equipmentCost: 5000, materials: [{name: 'Planta', unit: 'gl', quantityPerUnit: 1, unitPrice: 50000}] },
    { name: '24. Acometida eléctrica', unit: 'global', laborCost: 3000, equipmentCost: 1000, materials: [{name: 'Materiales acometida', unit: 'gl', quantityPerUnit: 1, unitPrice: 5000}] },
    { name: '25. Iluminación exterior', unit: 'unidad', laborCost: 300, equipmentCost: 1000, materials: [{name: 'Poste solar/led', unit: 'u', quantityPerUnit: 1, unitPrice: 3500}] },
    { name: '26. Rótulo identificación', unit: 'global', laborCost: 1000, equipmentCost: 500, materials: [{name: 'Rótulo concreto/metal', unit: 'gl', quantityPerUnit: 1, unitPrice: 4500}] },
    { name: '27. Jardinerización', unit: 'm2', laborCost: 20, equipmentCost: 5, materials: [{name: 'Plantas', unit: 'm2', quantityPerUnit: 1, unitPrice: 60}] },
    { name: '28. Equipamiento cocina (Escuelas)', unit: 'global', laborCost: 1000, equipmentCost: 0, materials: [{name: 'Estufa/Pila', unit: 'gl', quantityPerUnit: 1, unitPrice: 5000}] },
    { name: '29. Aulas provisionales', unit: 'm2', laborCost: 150, equipmentCost: 20, materials: [{name: 'Materiales livianos', unit: 'm2', quantityPerUnit: 1, unitPrice: 600}] },
    { name: '30. Inauguración y entrega', unit: 'global', laborCost: 2000, equipmentCost: 0, materials: [] },
  ]
};

// Roof-type packages (APU templates) to be merged into Presupuestos.
// Quantities are user-entered in the UI; these templates provide unit factors and materials.
export const DEFAULT_ROOF_BUDGET_LINES: Record<RoofType, Partial<BudgetLine>[]> = {
  LOSA_SOLIDA: [
    {
      name: 'Techo: Losa sólida (concreto armado)',
      unit: 'm2',
      laborCost: 160,
      equipmentCost: 45,
      materials: [
        { name: 'Concreto 3000psi', unit: 'm3', quantityPerUnit: 0.12, unitPrice: 1250 },
        { name: 'Acero refuerzo', unit: 'qq', quantityPerUnit: 0.12, unitPrice: 480 },
        { name: 'Formaleta', unit: 'm2', quantityPerUnit: 1.05, unitPrice: 55 },
      ],
    },
    {
      name: 'Techo: Impermeabilización',
      unit: 'm2',
      laborCost: 25,
      equipmentCost: 5,
      materials: [{ name: 'Impermeabilizante', unit: 'gal', quantityPerUnit: 0.1, unitPrice: 150 }],
    },
  ],
  LOSA_PREFABRICADA: [
    {
      name: 'Techo: Losa prefabricada (vigueta + bovedilla)',
      unit: 'm2',
      laborCost: 140,
      equipmentCost: 35,
      materials: [
        { name: 'Vigueta/Bovedilla', unit: 'm2', quantityPerUnit: 1.0, unitPrice: 280 },
        { name: 'Electro malla', unit: 'm2', quantityPerUnit: 1.1, unitPrice: 15 },
        { name: 'Concreto', unit: 'm3', quantityPerUnit: 0.08, unitPrice: 1200 },
      ],
    },
    {
      name: 'Techo: Masillado/afinamiento',
      unit: 'm2',
      laborCost: 30,
      equipmentCost: 0,
      materials: [{ name: 'Mortero', unit: 'm3', quantityPerUnit: 0.01, unitPrice: 800 }],
    },
    {
      name: 'Techo: Impermeabilización',
      unit: 'm2',
      laborCost: 25,
      equipmentCost: 5,
      materials: [{ name: 'Impermeabilizante', unit: 'gal', quantityPerUnit: 0.1, unitPrice: 150 }],
    },
  ],
  ESTRUCTURA_METALICA: [
    {
      name: 'Techo: Estructura metálica',
      unit: 'm2',
      laborCost: 65,
      equipmentCost: 15,
      materials: [
        { name: 'Perfil estructural', unit: 'kg', quantityPerUnit: 10, unitPrice: 16 },
        { name: 'Tornillería', unit: 'gl', quantityPerUnit: 0.02, unitPrice: 350 },
        { name: 'Anticorrosivo/Pintura', unit: 'gl', quantityPerUnit: 0.03, unitPrice: 650 },
      ],
    },
    {
      name: 'Techo: Cubierta lámina (aluzinc/galv.)',
      unit: 'm2',
      laborCost: 30,
      equipmentCost: 10,
      materials: [{ name: 'Lámina', unit: 'm2', quantityPerUnit: 1.1, unitPrice: 90 }],
    },
    {
      name: 'Techo: Canales y bajantes',
      unit: 'ml',
      laborCost: 25,
      equipmentCost: 5,
      materials: [{ name: 'Canaleta/Bajante', unit: 'ml', quantityPerUnit: 1.0, unitPrice: 85 }],
    },
  ],
  PERGOLA_MADERA: [
    {
      name: 'Techo: Pérgola de madera (estructura)',
      unit: 'm2',
      laborCost: 55,
      equipmentCost: 10,
      materials: [
        { name: 'Madera tratada', unit: 'pt', quantityPerUnit: 6, unitPrice: 14 },
        { name: 'Tornillería/Conectores', unit: 'gl', quantityPerUnit: 0.03, unitPrice: 380 },
        { name: 'Barniz/Protector', unit: 'gl', quantityPerUnit: 0.02, unitPrice: 220 },
      ],
    },
  ],
  PERGOLA_METAL: [
    {
      name: 'Techo: Pérgola metálica (estructura)',
      unit: 'm2',
      laborCost: 60,
      equipmentCost: 12,
      materials: [
        { name: 'Perfil metálico', unit: 'kg', quantityPerUnit: 8, unitPrice: 16 },
        { name: 'Tornillería', unit: 'gl', quantityPerUnit: 0.02, unitPrice: 350 },
        { name: 'Pintura/Anticorrosivo', unit: 'gl', quantityPerUnit: 0.03, unitPrice: 650 },
      ],
    },
  ],
};